### ISSUE TITLE
Option for creating a sharing URL

### ISSUE THREAD

**Issue by mschaaf** [prahladyeri/tuxdrive#1]
Thanks for the tool.
How about adding the functionality to create a public sharing URL for an uploaded file.
My use case is to upload via a script and return afterwards a URL  for sharing from the script.

**Comment by prahladyeri** [comment]
@mschaaf Thanks for bringing this feature to my notice. Added the `share` command in the latest release, download it from [here](https://prahladyeri.github.io/tuxdrive/). The commands are as follows:

    share alice.txt # publicly shares alice.txt in drive folder, prints link.
    share alice.txt alice@gmail.com # shares alice.txt in drive folder with alice@gmail.com, prints link.
    list permissions alice.txt # lists all share permissions on alice.txt
    clear permissions alice.txt # clears all share permissions on alice.txt

Test this release and let me know how it goes.

**Comment by mschaaf** [comment]
Thank you, I will give it a try.

**Comment by prahladyeri** [comment]
@mschaff let me know whether your issue was solved in the new version of tuxdrive, so I can close this.

**Comment by mschaaf** [comment]
@prahladyeri Yes it works and the issue can be closed. I use it right now in a script which I use inside of weechat. Thanks very useful tool.
