### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by hutber** [prahladyeri/tuxdrive#5]
I have done a fresh install and followed the instructions from https://www.ostechnix.com/tuxdrive-commandline-google-drive-client-linux/ 

However I could see no instructions on how to get a token.

```hutber@hutber:~$ tuxdrive --noauth_local_webserver
Traceback (most recent call last):
  File "/usr/bin/tuxdrive", line 8, in <module>
    from oauth2client import client
ModuleNotFoundError: No module named 'oauth2client```

**Comment by prahladyeri** [comment]
Hey @hutber, please ensure that you've installed pre-requisites for `tuxdrive` as follows:

    sudo pip3 install google-api-python-client

[Here are the detailed installation instructions](https://github.com/prahladyeri/tuxdrive#installation)

**Comment by prahladyeri** [comment]
Closing bug as there is no update since 3 days.

**Comment by kevinoliveira** [comment]
Hello, i installed `google-api-python-client` and the error persists.

**Comment by kevinoliveira** [comment]
this worked for me, `pip3 install oauth2client`.
