### ISSUE TITLE
This app isn't verified

### ISSUE THREAD

**Issue by davidzoufaly** [prahladyeri/tuxdrive#9]
Hi,
trying to run your handy app but I get google error in verifying process with --noauth_local_webserver flag I am getting Google Error: This app isn't verified - This app hasn't been verified by Google yet.

Thank you

**Comment by ijf8090** [comment]
I got the same error - tried to follow this recommendation in the doc
"...you'll have to register your own app by going to the Google API Console, enable Drive API, create credentials and copy the client_id.json to your /etc/tuxdrive folder. "

STuggled through the Google API console, it does not create client_id.json file. I copied the key and over-wrote the key in the existing client_id.json file. Get the following error 
Authorization Error
Error 401: invalid_client
The OAuth client was not found.

Would appreciate any help you can provide.

Best.
Ian

**Comment by sanga04** [comment]
> I got the same error - tried to follow this recommendation in the doc
> "...you'll have to register your own app by going to the Google API Console, enable Drive API, create credentials and copy the client_id.json to your /etc/tuxdrive folder. "
> 
> Struggled through the Google API console, it does not create client_id.json file. I copied the key and over-wrote the key in the existing client_id.json file. Get the following error
> Authorization Error
> Error 401: invalid_client
> The OAuth client was not found.
> 
> Would appreciate any help you can provide.
> 
> Best.
> Ian

it did for me, after you enable API, under Credentials when you click on CREATE CREDENTIALS choose OAuthClientID . it will work.

**Comment by Rriggs95** [comment]
Hey there, Super Noob here.

Quick question: when creating the credentials in the Google API Console, what type of app do you choose? Does it make a difference? I mean when it asks for application type and you are allowed to choose between Web App, Android App etc.. I followed the all the previous instructions with the option Desktop App and it didn't work, that's why I ask.

**Comment by prahladyeri** [comment]
> Quick question: when creating the credentials in the Google API Console, what type of app do you choose? Does it make a difference? I mean when it asks for application type and you are allowed to choose between Web App, Android App etc.. I followed the all the previous instructions with the option Desktop App and it didn't work, that's why I ask.

@Rriggs95 you must choose the Desktop App. Make sure you upgrade to the latest version and download the `client_id.json` file to your current path before running the app.

**Comment by prahladyeri** [comment]
> This app isn't verified - This app hasn't been verified by Google yet.

Yep, Google has recently changed the policy. You'll get the "This app isn't verified error" if you are a new developer without lots of street cred. You'll have to add a security exception to proceed, refer to this screenshot:

https://raw.githubusercontent.com/prahladyeri/prahladyeri.com/gh-pages/uploads/google_app_no_street_cred.png

**Comment by prahladyeri** [comment]
I've updated the README with details regarding the app verification error, closing this bug report.
